version: '3.8'  # No incluyas esta línea si ya eliminaste `version`

services:
  web:
    build:
      context: .  # Usa la carpeta actual
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Mapea el puerto 80 del contenedor al puerto 8080 de tu máquina
